name: chatrooms
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  firebase_messaging: ^6.0.16
  cloud_firestore: ^0.13.7
  firebase_auth: ^0.16.0
  firebase_database: ^3.1.6
  random_color: ^1.0.5
  provider: ^4.3.1
  modal_progress_hud: ^0.1.3
  uuid: ^2.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true